apiVersion: apps/v1
kind: Deployment
metadata:
  name: techno-app
  labels:
    app: techno-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: techno-app
  template:
    metadata:
      labels:
        app: techno-app
    spec:
      containers:
      - name: techno-app
        image: $ECR_REGISTRY/$ECR_REPOSITORY:${GITHUB_REF_NAME}
        ports:
        - containerPort: 2000
        env:
        - name: AWS_ACCESS_KEY_ID
          value: $AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          value: $AWS_SECRET_ACCESS_KEY
        - name: AWS_SESSION_TOKEN
          value: $AWS_SESSION_TOKEN
        - name: AWS_REGION
          value: $AWS_REGION
        - name: "ATHENA_DB"
          value: "rekognition_results_db"
        - name: "S3_STAGING_DIR"
          value: "s3://technooutput-denpasar-arif/"
        - name: "FLASK_SECRET_KEY"
          value: "lks"
        - name: "API_GATEWAY_URL"
          value: "https://sfieyabv83.execute-api.us-east-1.amazonaws.com/dev"
        - name: "SNS_TOPIC_ARN"
          value: "arn:aws:sns:us-east-1:467350923741:techno-sns-denpasar-arif"
        - name: "ATHENA_SCHEMA_NAME"
          value: "rekognition_results_db"
